app default {
	enable_default_driver = true;
	card_drivers = gids, internal;

	card_atr 3B:DF:96:00:81:31:FE:45:80:73:84:21:E0:55:69:78:54:00:01:83:0F:90:00:F9 {
		driver = "gids";
		name = "DNIe Peru";
		read_only = true;
	}
}

app cardmod {
}
